baseURL = 'https://mew-list.netlify.app/'
languageCode = 'en-us'
title = 'MEW List'

########################## Permalinks ############################
[permalinks.page]
"pages" = "/:slugorfilename/"

############################# Modules ############################
[module]
[[module.mounts]]
source = "assets"
target = "assets"

########## BUILD ##########
[build]
noJSConfigInAssets = false
useResourceCacheWhen = 'fallback'
[build.buildStats]
enable = true
[[build.cachebusters]]
source = 'assets/watching/hugo_stats\.json'
target = 'style\.css'
[[build.cachebusters]]
source = 'assets/.*\.(js|ts|jsx|tsx)'
target = 'js'
[[build.cachebusters]]
source = 'assets/.*\.(css|scss|sass)'
target = 'css'
[[build.cachebusters]]
source = 'assets/.*\.(.*)$'
target = '$1'

############################# Outputs ##############################
[outputs]
home = ['HTML', 'RSS', 'WebAppManifest']

############################ Media types ############################
[mediaTypes]
[mediaTypes."application/manifest+json"]
suffixes = ["webmanifest"]

############################ Output Format ###########################
[outputFormats]
[outputFormats.WebAppManifest]
mediaType = "application/manifest+json"
rel = "manifest"